### ISSUE TITLE
[github] Mention setting develop as default

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/developer-manual#16]
Mention setting develop as default while commenting on gitflow.

**Comment by jgvictores** [comment]
Origin of issue: https://github.com/roboticslab-uc3m/teo-simox-models/issues/1

**Comment by PeterBowman** [comment]
Related: #6. That is, don't bother to enforce the `master`/`develop` branch pair on non-Gitflow repos.

**Comment by jgvictores** [comment]
> Related: #6. That is, don't bother to enforce the `master`/`develop` branch pair on non-Gitflow repos.

Yes, yes! Of course, totally agreed.

**Comment by PeterBowman** [comment]
Closing as wontfix per https://github.com/roboticslab-uc3m/questions-and-answers/issues/88, `develop` is no longer referenced as of https://github.com/roboticslab-uc3m/developer-manual/commit/736706e6f7c56802790ae0b9f1244898d3771c2b.
