### ISSUE TITLE
Add intro for very-beginners

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/developer-manual#29]
Add intro for very-begginers:
- installing linux (VM vs partition)
- version control
- github (issues, etc)
- markdown (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
- doxygen

We actually have some good things at https://github.com/asrob-uc3m/tutoriales

**Comment by davidvelascogarcia** [comment]
@jgvictores quizá pueda resultar útil algún concepto. Lo fuí preparando sobre la marcha cuando empecé con Git y con MARKDOWN.

[Sintaxis Git](https://github.com/davidvelascogarcia/Git)
[Sintaxis MARKDOWN](https://github.com/davidvelascogarcia/MARKDOWN)

Lo acabo de subir a un repo.

**Comment by jgvictores** [comment]
Gracias @davidvelascogarcia !!

Como ves le hemos dedicado un ratillo a mejorar https://github.com/asrob-uc3m/tutoriales/blob/master/software/version-control/git.md ^^ ([estado actual](https://github.com/asrob-uc3m/tutoriales/blob/5fcd94b2e61ce57467f657b7a05c2bbda39e4403/software/version-control/git.md)).

**Comment by jgvictores** [comment]
Added main-developer-tools.md section at d0222e0c90f5284eecd8145353d7bb501927de81

**Comment by jgvictores** [comment]
Closing as https://github.com/roboticslab-uc3m/developer-manual/blob/master/main-developer-tools.md ([permalink](https://github.com/roboticslab-uc3m/developer-manual/blob/e62ba54caf4d240837c3f1c657699cec375d359a/main-developer-tools.md)) is proving to be good for this. All contributions will be incremental improvements.
