### ISSUE TITLE
Language for docs

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/developer-manual#35]
I want to open a debate of whether we should have our developer manual written mainly in Spanish or English.

I'll add some reasons I came up with:

### Reasons for Spanish:

1. This is mainly targeted to developers working at our lab, whose language is typically Spanish.
2. Spaniards typically communicate (read and write) much better in Spanish [1]

-- Insert here reasons --

### Reasons for English:

1. https://github.com/roboticslab-uc3m/developer-manual/issues/27
2. This is mainly targeted to developers working at our lab, whose main objective is to publish papers in English
3. Same language across all repositories of the organization
4. Internationalization: bilingual careers, people that come from abroad, external collaborators
5. (@jgvictores rant where there may seem to be a small contradiction but that's not a problem because @jgvictores has no clear preference at time of writing) Maybe it's not even such an issue, I'm exporting all non-roboticslab-specific documentation to be in Spanish at https://github.com/asrob-uc3m/tutoriales (example: https://github.com/asrob-uc3m/tutoriales/issues/20)

-- Insert here reasons --

[1] https://elpais.com/elpais/2017/01/04/inenglish/1483542724_068710.html

**Comment by PeterBowman** [comment]
+1 for English per #27 (note we had *both* prior to that).

**Comment by jgvictores** [comment]
+4 for English, with no no clear preference at time of writing.

Feel free to add a "label::santa:2:santa:"(TM @PeterBowman) anyone. :smile:

**Comment by jgvictores** [comment]
![photo_2019-01-08_19-03-12](https://user-images.githubusercontent.com/4448588/50849744-22102f00-1378-11e9-81d2-b25e87d712d8.jpg)

**Comment by PeterBowman** [comment]
A dlaczego nie po polsku?

**Comment by jgvictores** [comment]
Ni povus ankaŭ akceli Esperanton, pro ĝia internacia karaktero 😄

**Comment by PeterBowman** [comment]
Jest konsensus i już dawno całkiem przeszliśmy na angielski, zamykam.

**Comment by jgvictores** [comment]
Doskonały!
