### ISSUE TITLE
Consistent device and module destruction (YARP/C++)

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/developer-manual#44]
From https://github.com/robotology/yarp/issues/1952 (thoughts on `RFModule::close`):

> I'll adhere to the following policy: if there exists a `close` method that needs to release unmanaged resources (dynamically allocated memory) or terminate stuff in an ordered manner (if using PolyDriver class members, e.g. close device A before device B), always define a class destructor that calls `close`, be it a `DeviceDriver` or an `RFModule` derived class. Also, make sure nothing bad happens if this `close` method is called several times (i.e. set dangling pointers to `nullptr`). Why is that:
> 
> * `PolyDriver::open` may fail to initialize a subdevice, but it does **not** call the subdevice's `close` method; instead, it is immediately destructed via `delete` ([ref](https://github.com/robotology/yarp/blob/b3dff81c3739112b8f65cfd808f129bcbf4e7aa5/src/libYARP_dev/src/yarp/dev/PolyDriver.cpp#L308)).
> 
> * If `RFModule::configure` returns `false`, as explained in the above comments, `close` will never be called, hence I also want to use a destructor here.
> 
> * `PolyDriver::close` will never close a wrapped device twice, but callers of `RFModule` can do that inadvertently because of the previous point: once after a successful `RFModule::configure` and a CTRL+C signal (it just stops execution flow and calls `close` before leaving `runModule`), and one more time on class destruction.
> 
> * Despite those two mechanisms being relatively different, this policy ensures I treat both `RFModule` and `DeviceDriver` constructs in a similar manner: `close()` on destruction, avoid dangling pointers.

Some time ago, I adopted a verbose idiom on `RFModule` callers, that is, I made sure such an instance calls `RFModule::close` on unsuccessful configuration (see code example in linked YARP issue). I recently noticed (after an ugly segfault due to unreleased dynamic resources) it is best to embrace OO idioms (class destructors) and homogenize the way devices and modules are developed: see https://github.com/roboticslab-uc3m/yarp-devices/commit/666f8a412b34f61dcf4307e2255d12e68b85d06c (+ https://github.com/roboticslab-uc3m/yarp-devices/commit/99a8af25044a4ccab671915405bfa91c96f37542).

**Comment by jgvictores** [comment]
Added at new http://robots.uc3m.es/gitbook-developer-manual/best-practices-programming.html#programming-in-c-with-yarp, specifically http://robots.uc3m.es/gitbook-developer-manual/best-practices-programming.html#regarding-close via https://github.com/roboticslab-uc3m/developer-manual/commit/e53712c2af3452244226cd37f8f8463918589a7c
