### ISSUE TITLE
Neo 6M GPS Module light is not blinking

### ISSUE THREAD

**Issue by Fat-ima123** [roboticslab-uc3m/developer-manual#46]
Asslamualaikum!
Is there any one who helps me?
 I am using an esp 32 with NEO 6M gps module for tracking. My code was successfully uploaded but when i am looking for result on serial monitor it shows nothing other than...... Or ???????.
And also no light of gps module is blinking neither even the red/orange one nor the blue light.

**Comment by PeterBowman** [comment]
Hello, @Fat-ima123. Sorry, but I'm going to close this issue as out of the scope of this repo. I believe you will find useful answers to your question on Google, perhaps starting with [this](https://forum.arduino.cc/t/gy-neo-6mv2-modules-led-is-not-blinking/619447/3) or [this](https://portal.u-blox.com/s/question/0D52p00008v8it7CAA/gyneo6mv2-modules-led-is-not-blinking).
